# Generated by Django 4.0.1 on 2022-02-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0003_alter_primertabla_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primertabla',
            name='imagen',
        ),
    ]
